---
masterHosts_transport: "{% for host in groups['es-master-nodes'] %} {{hostvars[host]['ansible_eth1']['ipv4']['address'] }}:9301{% endfor %}"
es_data_dirs:
  - "/opt/elasticsearch/data"
es_log_dir: "/var/log/elasticsearch"
es_config:
  node.name: "{{ ansible_hostname }}"
  cluster.name: "test-cluster"
  network.host: ["{{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] }}","_local_" ]
  discovery.seed_hosts: "{{ masterHosts_transport.split() }}"
  http.port: 9201
  transport.port: 9301
  node.data: false
  node.master: true
  cluster.initial_master_nodes:
   - master-1
es_heap_size: 1g
es_api_port: 9201